Repository dolthub/doltgresql, pull requests merged in 2025-04, with the labels that each got.

#1388 [auto-bump] [no-release-notes] dependency by fulghum
  go.mod
  go.sum
Labels: dolt-bump

#1391 [auto-bump] [no-release-notes] dependency by fulghum
  go.mod
  go.sum
Labels: dolt-bump

#1412 [auto-bump] [no-release-notes] dependency by jycor
  go.mod
  go.sum
Labels: dolt-bump, contribution

#1414 [auto-bump] [no-release-notes] dependency by jycor
  go.mod
  go.sum
Labels: dolt-bump, contribution

#1411 Fixed interpretation calls within DML
  server/functions/framework/interpreted_function.go
  server/plpgsql/interpreter_logic.go
  testing/go/create_function_test.go
Labels: contribution

#1415 [auto-bump] [no-release-notes] dependency by zachmu
  go.mod
  go.sum
Labels: contribution

#1423 [auto-bump] [no-release-notes] dependency by fulghum
  go.mod
  go.sum
Labels: dolt-bump

#1442 [auto-bump] [no-release-notes] dependency by fulghum
  go.mod
  go.sum
Labels: dolt-bump
